# Generated by Django 2.0.6 on 2018-10-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='CURSO',
        ),
    ]
