# Generated by Django 2.1.2 on 2018-10-17 23:53

import contas.models.usuario
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_column='login', max_length=30, unique=True, verbose_name='Usuário')),
                ('password', models.CharField(db_column='senha', max_length=128, verbose_name='Senha')),
                ('data_expiracao', models.DateField(db_column='dtexpiracao', null=True, verbose_name='Data Expiração')),
                ('perfil', models.CharField(choices=[('C', 'Coordenador'), ('A', 'Aluno'), ('P', 'Professor')], max_length=1, verbose_name='Perfil')),
            ],
            options={
                'verbose_name': ('Usuário',),
                'verbose_name_plural': 'Usuários',
                'db_table': 'USUARIO',
            },
            managers=[
                ('objects', contas.models.usuario.UsusarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('celular', models.CharField(max_length=11, unique=True, verbose_name='Celular')),
                ('ra', models.CharField(max_length=7, unique=True, verbose_name='RA')),
                ('foto', models.ImageField(null=True, upload_to='', verbose_name='Foto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'ALUNO',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('celular', models.CharField(max_length=11, unique=True, verbose_name='Celular')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
                'db_table': 'COORDENADOR',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('celular', models.CharField(max_length=11, unique=True, verbose_name='Celular')),
                ('apelido', models.CharField(max_length=50, verbose_name='APELIDO')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'PROFESSOR',
            },
        ),
    ]
