# Generated by Django 2.1.2 on 2018-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, unique=True, verbose_name='Sigla')),
                ('sobre', models.TextField(null=True, verbose_name='Sobre o curso')),
                ('duracao', models.SmallIntegerField(verbose_name='Semestres')),
                ('tipo', models.CharField(choices=[('T', 'Tecnólogo')], max_length=1, verbose_name='Tipo')),
                ('noturno', models.BooleanField(verbose_name='Noturno?')),
                ('diurno', models.BooleanField(verbose_name='Diurno?')),
            ],
            options={
                'db_table': 'CURSO',
            },
        ),
    ]
